---
## General

tomcat_version: 8.5.53

## Service options

# Owner
tomcat_user: tomcat
tomcat_group: tomcat

# start on boot
tomcat_service_enabled: yes
# current state: started, stopped
tomcat_service_state: started

# Files & Paths
tomcat_install_path: "/opt/tomcat"
tomcat_bin_path: "{{ tomcat_install_path }}/bin"
tomcat_conf_path: "{{ tomcat_install_path }}/conf"
tomcat_webapps_path: "{{ tomcat_install_path }}/webapps"
