---

- name: Tomcat | Ensure tomcat group
  group:
    name: "{{ tomcat_group }}"

- name: Tomcat | Ensure tomcat user
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    shell: /bin/bash

- name: Tomcat | Create logs path
  file:
    path: "{{ tomcat_logs_path }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  when: tomcat_logs_path is defined

- name: Tomcat | Create install path
  file:
    path: "{{ tomcat_install_path }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: copy Tomcat
  copy:
    src: ./files/apache-tomcat-8.5.53.tar
    dest: /tmp/apache-tomcat-8.5.53.tar

- name: Tomcat | Download & Extract Tomcat
  unarchive:
    extra_opts: ['--strip-components=1']
    src: /tmp/apache-tomcat-8.5.53.tar
    remote_src: yes
    dest: "{{ tomcat_install_path }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0750

- name: Tomcat | Copy Daemon script
  template:
    src: tomcat.service.j2
    dest: /lib/systemd/system/tomcat.service
    mode: 0644
  notify: restart tomcat
