---
# tasks file for roles/bashrcsec
- name: Adding more details to history/bash_profile
  lineinfile:
    dest: "/etc/profile"
    state: present
    line: 'export HISTTIMEFORMAT="%d/%m/%y %T "'
    insertafter: 'EOF'